# Generated by Django 5.2.7 on 2025-11-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="apellido",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="usuario",
            name="nombre",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="usuario",
            name="telefono",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
